default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smile_dev
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASS") %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: smile_test
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASS") %>
  host: localhost
  port: 5432
  
production:
  <<: *default
  database: smile
  username: a123
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASS") %>
